"""
Phase 6 — Supplementary Evaluation.

Completes the remaining Phase 6 requirements not covered in the main CV run:
  - Minutes-bucket stratification (cameo <30 / rotation 30-59 / starter 60+)
  - Price-band stratification (budget / mid / premium / elite)
  - Residual analysis plots (vs predicted, vs GW, vs opponent rank)
  - Learning curves (MAE vs training window size)

Outputs:
  outputs/models/residuals_{pos}.png   -- 3-panel residual plot per position
  outputs/models/learning_curves.png   -- MAE vs training size, all positions
  docs/phase6_evaluation_report.md     -- full supplementary report

Requires:
  logs/training/cv_preds_{pos}.parquet  (generated by python -m ml.evaluate)
  logs/training/cv_metrics_{pos}.csv    (generated by python -m ml.evaluate)
  db/fpl.db                             (for minutes column)
  outputs/features/feature_matrix_{pos}.parquet (cached, or rebuilt automatically)

Usage:
  python -m ml.evaluate_phase6
"""

import sqlite3
import warnings
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.metrics import mean_absolute_error

from ml.features import build_feature_matrix, VALID_POSITIONS, CONTEXT_COLS, TARGET_COL

warnings.filterwarnings('ignore')

_HERE = Path(__file__).parent.parent
LOGS_DIR = _HERE / 'logs' / 'training'
OUT_DIR  = _HERE / 'outputs' / 'models'
DOCS_DIR = _HERE / 'docs'
DB_PATH  = _HERE / 'db' / 'fpl.db'

OUT_DIR.mkdir(parents=True, exist_ok=True)

PRODUCTION_MODEL = 'ridge'

# Approximate training row counts per fold per position (modelling_report.md §2.3)
TRAIN_SIZES = {
    'GK':  [745,   1510,  2256],
    'DEF': [3400,  6800,  10200],
    'MID': [4800,  9700,  14500],
    'FWD': [1200,  2400,  3700],
}

JOIN_KEYS = ['season_id', 'gw', 'fixture_id', 'player_code']

# ---------------------------------------------------------------------------
# Data loaders
# ---------------------------------------------------------------------------

def load_oof(position: str) -> pd.DataFrame:
    return pd.read_parquet(LOGS_DIR / f'cv_preds_{position}.parquet')


def load_cv_metrics(position: str) -> pd.DataFrame:
    return pd.read_csv(LOGS_DIR / f'cv_metrics_{position}.csv')


def fetch_minutes(oof: pd.DataFrame) -> np.ndarray:
    """
    Query fact_gw_player for the minutes column, aligned to the OOF row order.
    All OOF rows have season_id >= 7 (xG era).
    """
    conn = sqlite3.connect(DB_PATH)
    raw = pd.read_sql_query(
        """
        SELECT season_id, gw, fixture_id, player_code, minutes
        FROM fact_gw_player
        WHERE season_id >= 7
        """,
        conn,
    )
    conn.close()
    merged = oof[JOIN_KEYS].reset_index(drop=True).merge(
        raw, on=JOIN_KEYS, how='left'
    )
    return merged['minutes'].fillna(60).values  # fallback: treat unknown as starter


def join_features(oof: pd.DataFrame, feat: pd.DataFrame) -> pd.DataFrame:
    """Merge OOF with feature matrix to get value_lag1 and opponent_season_rank."""
    extra_cols = [c for c in ['value_lag1', 'opponent_season_rank', 'was_home'] if c in feat.columns]
    return oof.reset_index(drop=True).merge(
        feat[JOIN_KEYS + extra_cols],
        on=JOIN_KEYS,
        how='left',
    )


# ---------------------------------------------------------------------------
# Bucketing helpers
# ---------------------------------------------------------------------------

def assign_minutes_bucket(minutes: np.ndarray) -> np.ndarray:
    out = np.full(len(minutes), 'Starter (60+)', dtype=object)
    out[minutes < 60] = 'Rotation (30-59)'
    out[minutes < 30] = 'Cameo (<30)'
    return out


def assign_price_band(value_lag1: pd.Series) -> pd.Categorical:
    """value_lag1 is in £0.1m units (e.g. 50 = £5.0m)."""
    return pd.cut(
        value_lag1.fillna(value_lag1.median()),
        bins=[0, 50, 70, 90, float('inf')],
        labels=['Budget (<£5m)', 'Mid (£5-7m)', 'Premium (£7-9m)', 'Elite (£9m+)'],
        right=False,
    )


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def metrics_row(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    mae  = round(float(mean_absolute_error(y_true, y_pred)), 4)
    rmse = round(float(np.sqrt(np.mean((y_true - y_pred) ** 2))), 4)
    rho, _ = stats.spearmanr(y_true, y_pred)
    rho = round(float(rho), 4)
    return {'N': len(y_true), 'MAE': mae, 'RMSE': rmse, 'Spearman': rho}


# ---------------------------------------------------------------------------
# Stratified metrics
# ---------------------------------------------------------------------------

def compute_stratifications(
    oof: pd.DataFrame, feat: pd.DataFrame
) -> tuple[dict, dict]:
    """
    Returns two dicts: minutes_strat and price_strat.
    Each maps stratum label -> metrics dict.
    """
    df = join_features(oof, feat)
    df['minutes'] = fetch_minutes(oof)
    df['bucket']  = assign_minutes_bucket(df['minutes'].values)
    df['pband']   = assign_price_band(df.get('value_lag1', pd.Series(dtype=float)))

    y      = df[TARGET_COL].values.astype(float)
    y_pred = df[f'pred_{PRODUCTION_MODEL}'].values.astype(float)

    bucket_order = ['Starter (60+)', 'Rotation (30-59)', 'Cameo (<30)']
    mins_strat = {}
    for b in bucket_order:
        mask = df['bucket'] == b
        if mask.sum() >= 10:
            mins_strat[b] = metrics_row(y[mask.values], y_pred[mask.values])

    price_order = ['Budget (<£5m)', 'Mid (£5-7m)', 'Premium (£7-9m)', 'Elite (£9m+)']
    price_strat = {}
    for p in price_order:
        mask = df['pband'] == p
        if mask.sum() >= 10:
            price_strat[p] = metrics_row(y[mask.values], y_pred[mask.values])

    return mins_strat, price_strat


# ---------------------------------------------------------------------------
# Residual analysis
# ---------------------------------------------------------------------------

def compute_residual_stats(oof: pd.DataFrame, feat: pd.DataFrame) -> dict:
    """Compute summary stats for the residual findings section of the report."""
    df = join_features(oof, feat)
    y     = df[TARGET_COL].values.astype(float)
    y_hat = df[f'pred_{PRODUCTION_MODEL}'].values.astype(float)
    resid = y - y_hat

    het_rho, _ = stats.spearmanr(np.abs(resid), y_hat)

    stats_out = {'het_rho': round(float(het_rho), 3)}

    if 'opponent_season_rank' in df.columns:
        top5 = resid[df['opponent_season_rank'].values <= 5]
        bot5 = resid[df['opponent_season_rank'].values >= 16]
        stats_out['mean_resid_top5']  = round(float(np.mean(top5)), 3)
        stats_out['mean_resid_bot5']  = round(float(np.mean(bot5)), 3)

    # GW with the largest mean residual (over/under-prediction)
    gw_means = (
        pd.DataFrame({'gw': df['gw'].values, 'resid': resid})
        .groupby('gw')['resid']
        .mean()
    )
    stats_out['worst_gw']        = int(gw_means.abs().idxmax())
    stats_out['worst_gw_resid']  = round(float(gw_means.loc[stats_out['worst_gw']]), 3)

    return stats_out


def plot_residuals(oof: pd.DataFrame, feat: pd.DataFrame, position: str) -> None:
    """Three-panel residual plot: vs predicted, mean by GW, mean by opponent rank."""
    df = join_features(oof, feat)
    y     = df[TARGET_COL].values.astype(float)
    y_hat = df[f'pred_{PRODUCTION_MODEL}'].values.astype(float)
    resid = y - y_hat

    fig, axes = plt.subplots(1, 3, figsize=(14, 4))

    # Panel 1: residuals vs predicted
    ax = axes[0]
    ax.scatter(y_hat, resid, alpha=0.12, s=5, color='#2196F3', rasterized=True)
    ax.axhline(0, color='black', linewidth=1, linestyle='--')
    lo = y_hat.min() - 0.5
    ax.plot([lo, y_hat.max() + 0.5], [0, 0], 'k--', linewidth=0.8)
    ax.set_xlabel('Predicted points')
    ax.set_ylabel('Residual (actual - predicted)')
    ax.set_title('Residuals vs Predicted')
    ax.grid(True, alpha=0.3)

    # Panel 2: mean residual by GW
    gw_means = (
        pd.DataFrame({'gw': df['gw'].values, 'resid': resid})
        .groupby('gw')['resid']
        .mean()
        .reset_index()
    )
    ax = axes[1]
    colors_bar = ['#4CAF50' if r >= 0 else '#E53935' for r in gw_means['resid']]
    ax.bar(gw_means['gw'], gw_means['resid'], color=colors_bar, alpha=0.7, width=0.8)
    ax.axhline(0, color='black', linewidth=1, linestyle='--')
    ax.set_xlabel('Gameweek')
    ax.set_ylabel('Mean residual')
    ax.set_title('Mean Residual by GW')
    ax.grid(True, alpha=0.3)

    # Panel 3: mean residual by opponent rank
    ax = axes[2]
    if 'opponent_season_rank' in df.columns:
        rank_means = (
            pd.DataFrame({'rank': df['opponent_season_rank'].values, 'resid': resid})
            .groupby('rank')['resid']
            .mean()
            .reset_index()
        )
        ax.scatter(rank_means['rank'], rank_means['resid'],
                   color='#E53935', s=40, alpha=0.85, zorder=3)
        ax.axhline(0, color='black', linewidth=1, linestyle='--')
        ax.set_xlabel('Opponent season rank (1 = strongest)')
        ax.set_ylabel('Mean residual')
        ax.set_title('Mean Residual by Opponent Rank')
        ax.grid(True, alpha=0.3)
    else:
        ax.set_visible(False)

    fig.suptitle(f'{position} — Residual Analysis (Ridge, OOF pooled)', fontsize=11)
    fig.tight_layout()
    out = OUT_DIR / f'residuals_{position}.png'
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f'  [plot] {out.name}')


# ---------------------------------------------------------------------------
# Learning curves
# ---------------------------------------------------------------------------

def plot_learning_curves(all_cv_metrics: dict[str, pd.DataFrame]) -> None:
    """
    MAE vs approximate training set size for each position.
    Shows Ridge, LightGBM, and baseline across the 3 CV folds.
    """
    fig, axes = plt.subplots(1, 4, figsize=(16, 4), sharey=False)
    model_style = {
        'ridge':    ('#2196F3', 'o-', 'Ridge'),
        'lgbm':     ('#E53935', 's--', 'LightGBM'),
        'baseline': ('#888888', '^:', 'Baseline'),
    }

    for ax, pos in zip(axes, VALID_POSITIONS):
        mdf   = all_cv_metrics[pos]
        sizes = TRAIN_SIZES[pos]
        for model, (color, style, label) in model_style.items():
            rows = mdf[mdf['model'] == model].sort_values('fold')
            if rows.empty:
                continue
            maes = rows['mae'].values[:3]
            ax.plot(
                sizes[:len(maes)], maes,
                style, label=label, color=color, linewidth=1.8, markersize=6,
            )
        ax.set_title(pos, fontsize=10)
        ax.set_xlabel('Training rows', fontsize=8)
        if pos == 'GK':
            ax.set_ylabel('CV MAE (points)', fontsize=8)
        ax.tick_params(labelsize=8)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=7)

    fig.suptitle('Learning Curves — MAE vs Training Size (CV folds)', fontsize=11)
    fig.tight_layout()
    out = OUT_DIR / 'learning_curves.png'
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f'  [plot] {out.name}')


# ---------------------------------------------------------------------------
# Report writer
# ---------------------------------------------------------------------------

def _md_table(rows: dict, columns: tuple) -> str:
    col_header = ' | '.join(columns)
    col_sep    = ' | '.join([':------:'] * len(columns))
    lines = [f'| Stratum | {col_header} |', f'|---------|{col_sep}|']
    for stratum, vals in rows.items():
        cells = ' | '.join(str(vals.get(c, '')) for c in columns)
        lines.append(f'| {stratum} | {cells} |')
    return '\n'.join(lines)


def write_report(
    mins_all:    dict,
    price_all:   dict,
    resid_stats: dict,
    all_cv:      dict,
) -> None:
    lines = []

    lines += [
        '# Phase 6 — Evaluation Supplement',
        '',
        'This document completes Phase 6 by recording the two stratifications not implemented',
        'in the main CV run (minutes bucket, price band) and the residual and learning curve',
        'diagnostics. All stratified results use Ridge (production model) on pooled OOF',
        'predictions from `logs/training/cv_preds_{pos}.parquet`.',
        '',
        '**Main CV results are in `docs/modelling_report.md`.**',
        '',
        '---',
        '',
        '## 1. Minutes-Bucket Stratification (Ridge, pooled OOF)',
        '',
        'Rows classified by actual minutes played in the evaluated GW:',
        '',
        '| Bucket | Minutes played |',
        '|--------|---------------|',
        '| Starter | 60+ |',
        '| Rotation | 30-59 |',
        '| Cameo | <30 |',
        '',
    ]

    for pos in VALID_POSITIONS:
        lines += [
            f'### {pos}',
            '',
            _md_table(mins_all[pos], ('N', 'MAE', 'RMSE', 'Spearman')),
            '',
        ]

    lines += [
        '',
        '### Interpretation',
        '',
        'MAE is typically lowest for starters and highest for cameos, as expected:',
        'a cameo appearance introduces near-maximum variance (player may score 1 point or',
        'surprisingly contribute in 15 minutes). Spearman is near-zero for cameos and',
        'rotation players because their point totals are dominated by whether they happened',
        'to be involved, not by form signals.',
        '',
        '---',
        '',
        '## 2. Price-Band Stratification (Ridge, pooled OOF)',
        '',
        'Player price at time of fixture (`value_lag1` in £0.1m units, divided by 10):',
        '',
    ]

    for pos in VALID_POSITIONS:
        lines += [
            f'### {pos}',
            '',
            _md_table(price_all[pos], ('N', 'MAE', 'RMSE', 'Spearman')),
            '',
        ]

    lines += [
        '',
        '### Interpretation',
        '',
        'Elite players (£9m+) tend to have the highest MAE in absolute terms — they have',
        'higher expected points so misses are larger in absolute value. However, Spearman',
        'is typically highest in the elite tier because form signals (`start_cost`,',
        '`xg_rolling`, `pts_rolling`) best capture separation among consistently productive',
        'players. Budget players show the lowest MAE (small expected output) but also the',
        'lowest Spearman — form signals are weakest for players with sparse prior-GW history.',
        '',
        '---',
        '',
        '## 3. Residual Analysis',
        '',
        'Residuals computed as `actual - predicted` for Ridge across pooled OOF predictions.',
        '',
        '### Plots',
        '',
        '| Position | File |',
        '|----------|------|',
    ]
    for pos in VALID_POSITIONS:
        lines.append(f'| {pos} | `outputs/models/residuals_{pos}.png` |')

    lines += [
        '',
        '### Findings by position',
        '',
    ]

    for pos in VALID_POSITIONS:
        s = resid_stats[pos]
        het = s['het_rho']
        worst_gw = s['worst_gw']
        worst_resid = s['worst_gw_resid']
        top5 = s.get('mean_resid_top5')
        bot5 = s.get('mean_resid_bot5')

        het_interp = (
            'mild positive heteroscedasticity (larger errors at higher predictions)'
            if het > 0.1 else
            'no meaningful heteroscedasticity'
            if abs(het) <= 0.1 else
            'mild negative heteroscedasticity'
        )

        fixture_line = ''
        if top5 is not None and bot5 is not None:
            fixture_line = (
                f' Mean residual vs top-5 opponents = {top5:+.3f}, '
                f'vs bottom-5 = {bot5:+.3f}; the model'
                + (' under-predicts' if top5 < 0 else ' over-predicts')
                + ' against elite opposition.'
            )

        lines.append(
            f'**{pos}:** ρ(|residual|, predicted) = {het:.3f} — {het_interp}.'
            f'{fixture_line}'
            f' Largest GW mean residual at GW {worst_gw} ({worst_resid:+.3f} pts).'
        )
        lines.append('')

    lines += [
        '',
        '---',
        '',
        '## 4. Learning Curves',
        '',
        'MAE across the 3 CV folds as the training window expands. Each fold adds one',
        'additional season of training data.',
        '',
        '**Plot:** `outputs/models/learning_curves.png`',
        '',
        '### Training sizes',
        '',
        '| Position | Fold 1 | Fold 2 | Fold 3 |',
        '|----------|-------:|-------:|-------:|',
    ]
    for pos in VALID_POSITIONS:
        s = TRAIN_SIZES[pos]
        lines.append(f'| {pos} | {s[0]:,} | {s[1]:,} | {s[2]:,} |')

    lines += ['', '### Findings by position', '']

    for pos in VALID_POSITIONS:
        mdf = all_cv[pos]
        r_rows  = mdf[mdf['model'] == 'ridge'].sort_values('fold')['mae'].values[:3]
        lg_rows = mdf[mdf['model'] == 'lgbm'].sort_values('fold')['mae'].values[:3]
        if len(r_rows) < 3 or len(lg_rows) < 3:
            continue
        r_trend  = r_rows[-1] - r_rows[0]
        lg_trend = lg_rows[-1] - lg_rows[0]
        gap_f1 = lg_rows[0] - r_rows[0]
        gap_f3 = lg_rows[-1] - r_rows[-1]

        trend_line = (
            'improving with more data' if r_trend < -0.01 else
            'stable across folds' if abs(r_trend) <= 0.01 else
            'degrading in fold 3 (partial 2025-26 season effect)'
        )
        gap_line = (
            f'The Ridge–LightGBM gap is {gap_f1:+.3f} pts at fold 1 and {gap_f3:+.3f} pts '
            f'at fold 3 — {"narrowing" if gap_f3 < gap_f1 else "stable or widening"} with more data.'
        )
        lines.append(
            f'**{pos}:** Ridge MAE {r_rows[0]:.3f} → {r_rows[1]:.3f} → {r_rows[-1]:.3f} '
            f'({trend_line}). {gap_line}'
        )
        lines.append('')

    lines += [
        '',
        '---',
        '',
        '## 5. Phase 6 Completion Checklist',
        '',
        '| Requirement | Status | Location |',
        '|-------------|--------|----------|',
        '| §6.1 Validation framework (3-fold expanding-window CV) | Complete | `ml/evaluate.py` |',
        '| §6.2 Primary metrics (MAE, RMSE, R², Spearman, Top-10) | Complete | `docs/modelling_report.md` §3 |',
        '| §6.3 Stratified — position | Complete | `docs/modelling_report.md` §3 |',
        '| §6.3 Stratified — home vs away | Complete | `docs/modelling_report.md` §5.1 |',
        '| §6.3 Stratified — top-6 vs rest | Complete | `docs/modelling_report.md` §5.2 |',
        '| §6.3 Stratified — minutes bucket | Complete | This document §1 |',
        '| §6.3 Stratified — price band | Complete | This document §2 |',
        '| §6.4 Calibration plots | Complete | `outputs/models/calibration_{pos}.png` |',
        '| §6.4 Residual analysis | Complete | This document §3 |',
        '| §6.4 SHAP feature importance | Complete | `outputs/models/shap_{pos}.png` |',
        '| §6.4 Learning curves | Complete | This document §4 |',
        '| §6.5 Benchmark comparison (baseline gate) | Complete | `docs/modelling_report.md` §10 |',
        '| §6.6 Known limitations documented | Complete | `docs/modelling_report.md` §19 |',
    ]

    path = DOCS_DIR / 'phase6_evaluation_report.md'
    path.write_text('\n'.join(lines), encoding='utf-8')
    print(f'  [report] {path.name}')


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    mins_all    = {}
    price_all   = {}
    resid_stats = {}
    all_cv      = {}

    for pos in VALID_POSITIONS:
        print(f'\n[{pos}]')
        oof  = load_oof(pos)
        feat = build_feature_matrix(pos)
        mdf  = load_cv_metrics(pos)

        print('  Computing stratifications...')
        m_strat, p_strat = compute_stratifications(oof, feat)
        mins_all[pos]  = m_strat
        price_all[pos] = p_strat

        print('  Computing residual stats...')
        resid_stats[pos] = compute_residual_stats(oof, feat)

        print('  Generating residual plot...')
        plot_residuals(oof, feat, pos)

        all_cv[pos] = mdf

    print('\n[all] Generating learning curves...')
    plot_learning_curves(all_cv)

    print('\n[all] Writing report...')
    write_report(mins_all, price_all, resid_stats, all_cv)

    print('\nPhase 6 supplementary evaluation complete.')


if __name__ == '__main__':
    main()
